- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "Install nodejs"
  become: yes
  apt:
    name: nodejs
    update_cache: yes

- name: "Install npm"
  become: yes
  apt:
    name: npm
    update_cache: yes

- name: "Create Directory"
  shell: mkdir -p ~/web/

- name: "Copy Index"
  copy: 
    src: index.js
    dest: ~/web/index.js

- name: "Install pm2"
  become: yes
  shell: npm install pm2 -g

- name: "Run Server"
  shell: pm2 start ~/web/index.js -f

