# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  delete-infra:
    steps:
      - run:
        name: Destro stack
        when: onfail
        command: aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}


orbs:
  # Declare pre0defined jobs
  welcome: circleci/welcome-orb@0.4.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: "Build Infra using CF"
          command: |
            aws cloudformation deploy \
                --template-file 'Excercise 7/infra.yml' \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  # config-infra:
  #   docker:
  #     - image: circleci/python
  #   steps:
  #     - checkout
  #     - add_ssh_keys:
  #         fingerprints: 
  #           - "64:40:a5:48:d0:c1:5f:94:f0:b8:2a:6c:bc:b4:f5:22"
      
  #     - run:
  #         name: "Update"
  #         command: sudo apt update

  #     - run:
  #         name: "Install Ansible"
  #         command: sudo apt install ansible --fix-missing
  #     - run:
  #         name: "Run Playbook"
  #         command: ansible-playbook -i 'Excercise 5'/inventory 'Excercise 5'/main.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: simulate error
          command: |
            return 1
      - delete-infra
  

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build-infra
      # - config-infra
      - smoke_test
