- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install nodejs"
  become: yes
  apt:
    name: nodejs
    update_cache: yes

- name: "Install npm"
  become: yes
  apt:
    name: npm
    update_cache: yes

- name: "Copy Index"
  copy: 
    src: index.js
    dest: ~/web/index.js

- name: "Install pm2"
  become: yes
  apt:
    name: pm2
    update_cache: yes

- name: "Run Server"
  become: yes
  shell: pm2 start ~/web/index.js -f

